### ISSUE TITLE
Missing macOS privacy manifests

### ISSUE THREAD

**Issue by bishalstha** [vishnuagbly/google_sign_in_all_platforms#11]
macOS privacy manifest enforcement has rolled out, so this brings all macOS plugins into alignment with iOS policy of always having a manifest, including updating the repo tooling to enforce that.

**Comment by vishnuagbly** [comment]
Hi, can you make a PR for this?

**Comment by vishnuagbly** [comment]
Addressed in latest version

**Comment by bishalstha** [comment]
Thank you for the notification.

Best regards
