### ISSUE TITLE
Question about how the library works

### ISSUE THREAD

**Issue by victoret7** [vishnuagbly/google_sign_in_all_platforms#4]
Is there a way to allow users to not have to log in every time you start the app?
With GoogleSignIn I used this code so that whenever the app got launched it remembered the user's account.
`  @override
  void initState() {
    super.initState();
    _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount? account) {
      setState(() {
        _isSignedIn = account != null;
      });
    });
    _googleSignIn.signInSilently();
  }`

**Comment by victoret7** [comment]
@vishnuagbly

**Comment by vishnuagbly** [comment]
Hii, here, you can directly call `signIn` method, and it will check for an existing token in the cache, and if that is available, it will automatically use that. You can look at documentation above each method [here](https://github.com/vishnuagbly/google_sign_in_all_platforms/blob/main/google_sign_in_all_platforms_interface/lib/google_sign_in_all_platforms_interface.dart), and also look at the [params file](https://github.com/vishnuagbly/google_sign_in_all_platforms/blob/main/google_sign_in_all_platforms_interface/lib/src/init_params.dart), for changing the save, load token functions.
