### ISSUE TITLE
clientId is not supported on Android and is interpreted as serverClientId. Use serverClientId instead to suppress this warning.

### ISSUE THREAD

**Issue by DataBPaidiatriko** [vishnuagbly/google_sign_in_all_platforms#7]
It seems there is an issue with google sign in for Android devices.

If I use the below code from the example
```
_googleSignIn = GoogleSignIn(
  params: const GoogleSignInParams(
    clientId: 'xxxx',
  )
);
```
I am getting an error `PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)` and looking at the debug log it shows the message `clientId is not supported on Android and is interpreted as serverClientId. Use serverClientId instead to suppress this warning.`

If I use the below code
```
_googleSignIn = GoogleSignIn(
  params: const GoogleSignInParams(
    clientId: null,
  )
);
```
I am getting an error from the library that clientId is required for Android.

If I remove
```
        assert(
          !Platform.isAndroid || params.clientId != null,
          'For Android, clientId cannot be null',
        )
```
from `google_sign_in_all_platforms/google_sign_in_all_platforms.dart` and try with
```
_googleSignIn = GoogleSignIn(
  params: const GoogleSignInParams(
  )
);
```
then Google sign in works in Android emulator Pixel_3a_API_34_extension_level_7

I am not sure if I should create a pull request to remove the assert or not.
Please advice.

**Comment by vishnuagbly** [comment]
@DataBPaidiatriko I have been very busy, and was not able to basically work on this, because I didn't have the windows machine at the time. But now I finally got the time, and set up Parallels, which is working great. Has already been able to test it for Windows and MacOS.

I would like to connect with you. Let me know if you are interested.

**Comment by vishnuagbly** [comment]
For this issue, I will try to look into it further.

**Comment by vishnuagbly** [comment]
Fixed in the latest version !
